/* istanbul ignore file */

import { headers } from 'next/headers';
import { Session } from 'next-auth';
import { ReactNode } from 'react';

import AuthContext from '../../context/AuthContext';

export const metadata = {
  title: 'Secured Page',
  description: 'Generated by Next.js',
};

async function getSession(cookie: string): Promise<Session> {
  const response = await fetch(`${process.env.NEXTAUTH_URL}/api/auth/session`, {
    headers: {
      cookie,
    },
  });

  const session = await response.json();

  return Object.keys(session).length > 0 ? session : null;
}

export default async function RootLayout({ children }: { children: ReactNode }) {
  const session = await getSession(headers().get('cookie') ?? '');

  return <AuthContext session={session}>{children}</AuthContext>;
}
