parameters:
  - name: environmentType
    type: string
    values:
      - Dev
      - QA
      - Prod

  - name: slotName
    type: string
    default: production

  - name: regions
    type: object
    default:
      - East

  - name: serviceConnection
    type: string

jobs:
  - ${{ each region in parameters.regions }}:
      - deployment: jobDeploy${{ region }}
        displayName: Deploy ${{ region }}-${{ parameters.slotName }}
        environment: ${{ parameters.environmentType }}
        variables:
          ciBuildNumber: $(Build.BuildNumber)x$(System.JobAttempt)
          resourceGroupName: $(resourceGroupPrefix)-$(appName)-${{ parameters.environmentType }}-${{ region }}
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: $(buildPackageName)

                - script: |
                    cat << EOF >> .env
                    CI_BUILD_NUMBER = $(ciBuildNumber)
                    EOF
                  displayName: Set BuildNumber
                  workingDirectory: $(Pipeline.Workspace)/$(buildPackageName)

                - task: AzureWebApp@1
                  name: taskDeployAppService
                  displayName: Azure Deploy
                  inputs:
                    azureSubscription: ${{ parameters.serviceConnection }}
                    resourceGroupName: $(resourceGroupName)
                    appType: webAppLinux
                    appName: $(resourceGroupName)
                    runtimeStack: $(runtimeStack)
                    package: $(Pipeline.Workspace)/$(buildPackageName)
                    slotName: ${{ parameters.slotName }}
                    startUpCommand: 'npm run start:prod'

                - bash: |
                    echo "##vso[task.setvariable variable=deployedAppUrl;isOutput=true;]$(taskDeployAppService.AppServiceApplicationUrl)"
                    echo "##vso[task.setvariable variable=deployedBuildNumber;isOutput=true;]$(ciBuildNumber)"
                  name: setDeploymentResults
                  displayName: Set Deployed App References

                - template: smokeTest.yml
                  parameters:
                    appUrl: $(taskDeployAppService.AppServiceApplicationUrl)
                    ciBuildNumber: $(ciBuildNumber)

                - script: env | sort
                  displayName: Pipeline Environment

      - job: jobDeployValidation${{ region }}
        displayName: E2E ${{ region }}-${{ parameters.slotName }}
        dependsOn: jobDeploy${{ region }}
        condition: and(succeeded(), eq('false', variables.skipE2eTests))
        variables:
          deployedAppUrl: $[ dependencies.jobDeploy${{ region }}.outputs['jobDeploy${{ region }}.setDeploymentResults.deployedAppUrl'] ]
          deployedBuildNumber: $[ dependencies.jobDeploy${{ region }}.outputs['jobDeploy${{ region }}.setDeploymentResults.deployedBuildNumber'] ]
        steps:
          - script: env | sort
            displayName: Pipeline Environment

          - template: npmInstall.yml

          - template: e2eTest.yml
            parameters:
              environmentType: ${{ parameters.environmentType }}
              slotName: ${{ parameters.slotName }}
              region: ${{ region }}
              serviceConnection: ${{ parameters.serviceConnection }}
              deployedAppUrl: $(deployedAppUrl)
              ciBuildNumber: $(deployedBuildNumber)
