parameters:
  - name: environmentType
    type: string
    values:
      - Dev
      - QA
      - Prod

  - name: slotName
    type: string
    default: staging

  - name: dependsOnDeployJob
    type: boolean
    default: true

  - name: serviceConnection
    type: string

  - name: regions
    type: object

jobs:
- ${{ each region in parameters.regions }}:
  - deployment: jobSwapSlot${{ region }}
    displayName: Swap Slot ${{ region }}
    environment: ${{ parameters.environmentType }}
    ${{ if and(eq(parameters.dependsOnDeployJob, true), eq(variables.skipE2eTests, false)) }}:
      dependsOn: jobDeployValidation${{ region }}
    ${{ elseif parameters.dependsOnDeployJob }}:
      dependsOn: jobDeploy${{ region }}
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none

            - task: AzureAppServiceManage@0
              displayName: Swap slot ${{ region }}
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                appType: webAppLinux
                webAppName: $(appName)-${{ parameters.environmentType }}-${{ region }}
                resourceGroupName: kmx-${{ parameters.environmentType }}-${{ region }}-$(appName)
                sourceSlot: ${{ parameters.slotName }}
                swapWithProduction: true

            - template: smokeTest.yml
              parameters:
                appUrl: 'https://$(appName)-${{ parameters.environmentType }}-${{ region }}.azurewebsites.net'

  - job: jobSwapValidation${{ region }}
    displayName: E2E Tests ${{ region }}
    dependsOn: jobSwapSlot${{ region }}
    condition: ${{ eq(variables.skipE2eTests, false) }}
    variables:
      deployedAppUrl: 'https://$(appName)-${{ parameters.environmentType }}-${{ region }}.azurewebsites.net'
    steps:
      - script: env | sort
        displayName: Pipeline Environment

      - template: npmInstall.yml

      - script: npm run test:e2e -- --config baseUrl=$(deployedAppUrl) -- --env $(Build.BuildNumber)
        displayName: Cypress
