parameters:
  - name: environmentType
    type: string
    values:
      - Dev
      - QA
      - Prod

  - name: slotName
    type: string
    default: staging

  - name: dependsOnDeployJob
    type: boolean
    default: true

  - name: serviceConnection
    type: string

  - name: regions
    type: object

jobs:
  - ${{ each region in parameters.regions }}:
      - deployment: jobSwapSlot${{ region }}
        displayName: SwapSlot ${{ region }}-production
        environment: ${{ parameters.environmentType }}
        ${{ if eq(parameters.dependsOnDeployJob, 'false') }}:
          dependsOn:
            - jobDeploy${{ region }}
            - jobDeployValidation${{ region }}
          condition: |
            and
            (
              in(dependencies.jobDeploy${{ region }}.result, 'Succeeded'),
              in(dependencies.jobDeployValidation${{ region }}.result, 'Succeeded', 'Skipped')
            )
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none

                - task: AzureAppServiceManage@0
                  displayName: SwapSlot
                  inputs:
                    azureSubscription: ${{ parameters.serviceConnection }}
                    appType: webAppLinux
                    webAppName: $(appName)-${{ parameters.environmentType }}-${{ region }}
                    resourceGroupName: kmx-${{ parameters.environmentType }}-${{ region }}-$(appName)
                    sourceSlot: ${{ parameters.slotName }}
                    swapWithProduction: true

                - template: smokeTest.yml
                  parameters:
                    appUrl: 'https://$(appName)-${{ parameters.environmentType }}-${{ region }}.azurewebsites.net'

      - job: jobSwapValidation${{ region }}
        displayName: E2E ${{ region }}-production
        dependsOn: jobSwapSlot${{ region }}
        condition: and(succeeded(), eq('false', variables.skipE2eTests))
        variables:
          deployedAppUrl: 'https://$(appName)-${{ parameters.environmentType }}-${{ region }}.azurewebsites.net'
        steps:
          - script: env | sort
            displayName: Pipeline Environment

          - template: npmInstall.yml

          - script: npm run test:e2e -- --config baseUrl=$(deployedAppUrl) -- --env $(Build.BuildNumber)
            displayName: Cypress
