parameters:
  - name: environmentType
    type: string
    values:
      - Dev
      - QA
      - Prod

  - name: regions
    type: object
    default:
      - East

  - name: serviceConnection
    type: string

  - name: manualApproval
    type: boolean
    default: false

jobs:
  - ${{ if parameters.manualApproval }}:
      - job: jobManualApproval
        displayName: Manual Approval
        pool: server
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 1
            inputs:
              instructions: |
                ✅ Acceptance criteria is met
                ✅ Regressions pass
              onTimeout: 'reject'

  - ${{ each region in parameters.regions }}:
      - deployment: jobDeploy${{ region }}
        displayName: Deploy ${{ region }}-${{ parameters.slotName }}
        environment: ${{ parameters.environmentType }}
        ${{ if parameters.manualApproval }}:
          dependsOn: jobManualApproval
        variables:
          ciBuildNumber: $(Build.BuildNumber)x$(System.JobAttempt)
          resourceGroupName: $(resourceGroupPrefix)-$(appName)-${{ parameters.environmentType }}-${{ region }}
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: $(buildPackageName)

                - script: |
                    cat << EOF >> .env
                    CI_BUILD_NUMBER = $(ciBuildNumber)
                    EOF
                  displayName: Set BuildNumber
                  workingDirectory: $(Pipeline.Workspace)/$(buildPackageName)

                #                - task: AzureWebApp@1
                #                  name: taskDeployAppService
                #                  displayName: Azure Deploy
                #                  inputs:
                #                    azureSubscription: ${{ parameters.serviceConnection }}
                #                    resourceGroupName: $(resourceGroupName)
                #                    appType: webAppLinux
                #                    appName: $(resourceGroupName)
                #                    runtimeStack: $(runtimeStack)
                #                    package: $(Pipeline.Workspace)/$(buildPackageName)
                #                    slotName: ${{ parameters.slotName }}
                #                    startUpCommand: 'npm run start:prod'

                - task: AzureCLI@2
                  displayName: 'Get ApiKey'
                  inputs:
                    azureSubscription: ${{ parameters.serviceConnection }}
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      resourceName=$(az resource list --resource-group $(resourceGroupName) --resource-type 'Microsoft.Web/staticSites' --query [].name --output tsv)
                      APIKEY=$(az staticwebapp secrets list --name $resourceName | jq -r '.properties.apiKey')
                      echo "##vso[task.setvariable variable=apiKey;issecret=true]$APIKEY"

                - script: env | sort
                  displayName: Pipeline Environment

                - task: AzureStaticWebApp@0
                  displayName: Azure Deploy
                  inputs:
                    azure_static_web_apps_api_token: $(apiKey)
                    app_location: '/' # App source code path
                    api_location: '' # Api source code path - optional
                    output_location: '' # Built app content directory - optional

                - bash: |
                    echo "##vso[task.setvariable variable=deployedAppUrl;isOutput=true;]$(taskDeployAppService.AppServiceApplicationUrl)"
                    echo "##vso[task.setvariable variable=deployedBuildNumber;isOutput=true;]$(ciBuildNumber)"
                  name: setDeploymentResults
                  displayName: Set Deployed App References

                - template: smokeTest.yml
                  parameters:
                    appUrl: $(taskDeployAppService.AppServiceApplicationUrl)
                    ciBuildNumber: $(ciBuildNumber)

                - script: env | sort
                  displayName: Pipeline Environment

      - job: jobDeployValidation${{ region }}
        displayName: E2E ${{ region }}-${{ parameters.slotName }}
        dependsOn: jobDeploy${{ region }}
        condition: and(succeeded(), eq('false', variables.skipE2eTests))
        variables:
          deployedAppUrl: $[ dependencies.jobDeploy${{ region }}.outputs['jobDeploy${{ region }}.setDeploymentResults.deployedAppUrl'] ]
          deployedBuildNumber: $[ dependencies.jobDeploy${{ region }}.outputs['jobDeploy${{ region }}.setDeploymentResults.deployedBuildNumber'] ]
        steps:
          - script: env | sort
            displayName: Pipeline Environment

          - template: npmInstall.yml

          - template: e2eTest.yml
            parameters:
              slotName: ${{ parameters.slotName }}
              region: ${{ region }}
              deployedAppUrl: $(deployedAppUrl)
              ciBuildNumber: $(deployedBuildNumber)
