import { InferGetStaticPropsType } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import styles from '../../styles/Home.module.css';
import DataRenderingDemo from '../components/DataRenderingDemo';
import Header from '../components/Header';
import usePosts from '../hooks/usePosts';
import { fetchPosts, Post } from '../services/postsService';

interface Props {
  props: {
    posts: Post[];
  };
}

export async function getStaticProps(): Promise<Props> {
  const posts = await fetchPosts();

  return {
    props: {
      posts,
    },
  };
}

export default function Home({ posts }: InferGetStaticPropsType<typeof getStaticProps>) {
  const { data: clientPosts } = usePosts();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />

        <DataRenderingDemo posts={posts} clientPosts={clientPosts} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
