/* istanbul ignore file */

import { ReactNode } from 'react';

import Layout from '../components/Layout';
import AppStateApp from '../context/AppStateApp';
import { setupMsw } from '../core/msw';

export const metadata = {
  title: 'Health Check',
  description: 'Generated by Next.js',
};

// /* istanbul ignore next */
// if (process.env.NEXT_PUBLIC_API_MOCKING === 'enabled') {
//   // eslint-disable-next-line @typescript-eslint/no-var-requires
//   const { setupMsw } = require('../core/msw');
//   void setupMsw();
// }

export default function RootLayout({ children }: { children: ReactNode }) {
  const avoidChromeExtensionWarning = true;

  return (
    <html lang="en">
      <body suppressHydrationWarning={avoidChromeExtensionWarning}>
        <AppStateApp>
          <Layout>{children}</Layout>
        </AppStateApp>
      </body>
    </html>
  );
}
