/* istanbul ignore file */

import { ReactNode } from 'react';

import Layout from '../components/Layout';
import AppStateApp from '../context/AppStateApp';

export const metadata = {
  title: 'Health Check',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  const avoidChromeExtensionWarning = true;

  return (
    <html lang="en">
      <body suppressHydrationWarning={avoidChromeExtensionWarning}>
        <AppStateApp>
          <Layout>{children}</Layout>
        </AppStateApp>
      </body>
    </html>
  );
}
