parameters:
  - name: deployedAppName
  - name: serviceConnection
    type: string

  - name: ciBuildNumber
    type: string


steps:
- task: AzureAppServiceSettings@1
  displayName: Azure App Service Settings
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    appName: ${{ parameters.deployedAppName }}
    # To deploy the settings on a slot, provide slot name as below. By default, the settings would be applied to the actual Web App (Production slot)
    slotName: service-staging
    generalSettings: |
      [
        {
          "startUpCommand": ""
        }
      ]
    appSettings: |
      [
        {
          "name": "CI_BUILD_NUMBER",
          "value": "${{ parameters.ciBuildNumber }}",
          "slotSetting": false
        },
        {
          "name": "CYPRESS_INSTALL_BINARY",
          "value": "0",
          "slotSetting": true
        },
        {
          "name": "MSW_MOCK",
          "value": "true",
          "slotSetting": false
        },
        {
          "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
          "value": "true",
          "slotSetting": true
        },
        {
          "name": "WEBSITE_ENABLE_SYNC_UPDATE_SITE",
          "value": "true",
          "slotSetting": true
        },
        {
          "name": "WEBSITE_HTTPLOGGING_RETENTION_DAYS",
          "value": "1",
          "slotSetting": false
        },
        {
          "name": "WEBSITE_NODE_DEFAULT_VERSION",
          "value": "14.17.4",
          "slotSetting": false
        },
        {
          "name": "WEBSITE_NPM_DEFAULT_VERSION",
          "value": "6",
          "slotSetting": false
        },
        {
          "name": "WEBSITE_SWAP_WARMUP_PING_PATH",
          "value": "/api/health",
          "slotSetting": false
        },
        {
          "name": "WEBSITE_SWAP_WARMUP_PING_STATUSES",
          "value": "200, 202",
          "slotSetting": false
        },
        {
          "name": "WEBSITE_WARMUP_PATH",
          "value": "/health",
          "slotSetting": false
        }
      ]
