parameters:
  - name: environmentType
    type: string
    values:
      - Dev
      - QA
      - Prod

  - name: slotName
    type: string
    default: production

  - name: regions
    type: object
    default:
      - East

  - name: serviceConnection
    type: string

  - name: manualApproval
    type: boolean
    default: false

jobs:
- ${{ if parameters.manualApproval }}:
  - job: jobManualApproval
    displayName: Manual Approval
    pool: server
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 1
        inputs:
          instructions: |
            ✅ Acceptance criteria is met
            ✅ Regressions pass
          onTimeout: 'reject'

- ${{ each region in parameters.regions }}:
    - deployment: jobDeploy${{ region }}
      displayName: Deploy ${{ region }}
      environment: ${{ parameters.environmentType }}
      ${{ if parameters.manualApproval }}:
        dependsOn: jobManualApproval
      variables:
        ciBuildNumber: $(Build.BuildNumber)_$(System.JobAttempt)
      pool:
        vmImage: ubuntu-latest
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureWebApp@1
                name: taskDeployAppService
                inputs:
                  azureSubscription: ${{ parameters.serviceConnection }}
                  appType: webAppLinux
                  appName: $(appName)-${{ parameters.environmentType }}-${{ region }}
                  runtimeStack: 'NODE|14-lts'
                  package: $(Pipeline.Workspace)/$(buildPackageName)
#                  startUpCommand: 'npm run start:prod'
                  resourceGroupName: kmx-${{ parameters.environmentType }}-${{ region }}-$(appName)
                  slotName: ${{ parameters.slotName }}
                  appSettings: -CI_BUILD_NUMBER $(ciBuildNumber) -WEBSITE_WARMUP_PATH "/health" -WEBSITE_SWAP_WARMUP_PING_STATUSES "200, 202"

              - bash: |
                  echo "AppServiceApplicationUrl is $(taskDeployAppService.AppServiceApplicationUrl)"
                  echo "##vso[task.setvariable variable=deployedAppUrl;isOutput=true;]$(taskDeployAppService.AppServiceApplicationUrl)"
                  echo "##vso[task.setvariable variable=ciBuildNumber;isOutput=true;]$(taskDeployAppService.ciBuildNumber)"
                name: setDeploymentResults
                displayName: Set deployedAppUrl

              - script: env | sort
                displayName: Pipeline Environment

    - job: jobDeployValidation${{ region }}
      displayName: E2E Tests ${{ region }}
      dependsOn: jobDeploy${{ region }}
      condition: ${{ eq(variables.skipE2eTests, false) }}
      variables:
        deployedAppUrl: $[ dependencies.jobDeploy${{ region }}.outputs['jobDeploy${{ region }}.setDeploymentResults.deployedAppUrl'] ]
        ciBuildNumber: $[ dependencies.jobDeploy${{ region }}.outputs['jobDeploy${{ region }}.setDeploymentResults.ciBuildNumber'] ]
      steps:
        - script: env | sort
          displayName: Pipeline Environment

        - template: npmInstall.yml

        - script: npm run test:e2e -- --config baseUrl=$(deployedAppUrl) -- --env $(ciBuildNumber)
          displayName: Cypress
