parameters:
  - name: appName
    type: string

  - name: slotName
    type: string
    default: staging

  - name: requireManual
    type: boolean
    default: false

  - name: resourceGroupName
    type: string

jobs:
  - deployment: jobSwapSlot
    displayName: Swap slot
    environment: ${{ parameters.environmentType }}
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo swap-slot
              displayName: Swap slot

  - job: jobDeployValidation
    displayName: E2E Tests
    dependsOn: jobSwapSlot
    variables:
      deployedAppUrl: $[ dependencies.jobDeploy.outputs['jobDeploy.setDeployedAppUrl.deployedAppUrl'] ]
    steps:
      - script: env | sort
        displayName: Pipeline Environment

      - script: echo build-artifact
        displayName: Build

#  - ${{ if eq(parameters.requireManual, true) }}:
#      - job:
#        displayName: Manual Approval
#        dependsOn: jobSwapSlot
#        pool: server
#        steps:
#          - task: ManualValidation@0
#            timeoutInMinutes: 1
#            inputs:
#              instructions: |
#                ✅ Acceptance criteria is met
#                ✅ Regressions pass
#              onTimeout: 'reject'
