parameters:
  - name: environmentTypes
    type: object
    values:
      - Dev
      - QA
      - Prod

  - name: regions
    type: object
    default:
      - East

  - name: serviceConnection
    type: string

jobs:
  - ${{ each environmentType in parameters.environmentTypes }}:
      - ${{ each region in parameters.regions }}:
          - job: deployResources_${{ environmentType }}_${{ region }}
            displayName: Deploy ${{ environmentType }} - ${{ region }}
            variables:
              regionName: ${{ lower(region) }}
              environmentName: ${{ lower(environmentType) }}
            steps:
              - template: azDeploy-resourceGroup.yml
                parameters:
                  action: create
                  environmentName: $(environmentName)
                  regionName: $(regionName)
                  serviceConnection: ${{ parameters.serviceConnection }}

              - template: azDeploy.yml
                parameters:
                  action: create
                  environmentName: $(environmentName)
                  regionName: $(regionName)
                  serviceConnection: ${{ parameters.serviceConnection }}
