trigger: none
pr:
  - main
  - master

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: skipE2eTests
    type: boolean
    default: false

variables:
  - template: templates/variables.yml
    parameters:
      skipE2eTests: ${{ parameters.skipE2eTests }}

jobs:
  - template: templates/build.yml
